### PR TITLE
Datagen Fixes

### LINKED ISSUE #3078: [💡]: Electronic Trowel
### Was this feature suggested before?

- [x] No, it was not.

### A list of popular features/mods the team has already considered and will not implement.

- [x] I understand :(

### What would you like to be added?

Add an electronic equivalent to a trowel

### Why is this needed?

I'd really like to avoid crafting hundreds of trowels for construction.
Because this is all I've managed to build with one trowel, and in my opinion, that's very little:
Image

I can also offer an option if the trowel can be repaired

### PR DESCRIPTION
**Pull request by Redeix**
- Fixed missing greenhouse casings from datagen
- Fixed wrong item textures for fish roe and proginator cells
- Fixed events bus being missing
- Added firmalife planter support for harvest baskets
- Updated the trowels to use the RNR recipes instead of manual mappings. And made them unbreakable.

Closes https://github.com/TerraFirmaGreg-Team/Modpack-Modern/issues/3078

### CODE REVIEW

File: src/main/java/su/terrafirmagreg/core/common/data/items/TrowelItem.java [hunk 1]
```diff
@@ -110,51 +64,37 @@ public static Map<ResourceLocation, ResourceLocation> createBlockMapping() {
...
         ResourceLocation clickedBlockId = clickedState.getBlock().builtInRegistryHolder().key().location();
 
-        Map<ResourceLocation, ResourceLocation> blockMapping = createBlockMapping();
-
-        // Exception for rnr roads.
-        if (clickedBlockId.toString().equals("rnr:base_course")) {
-            List<ItemStack> validStacks = new ArrayList<>();
-            // Randomly chooses a spot in the hotbar.
+        // RNR road exception. Use BlockModRecipe to find a matching recipe.
+        if (TFGModsResolver.RNR.isLoaded() && clickedBlockId.toString().equals("rnr:base_course")) {
```
Comment (Pyritie) [inline src/main/java/su/terrafirmagreg/core/common/data/items/TrowelItem.java:68]: if we have rnr as a dependency, wouldn't it be better to just check against its actual block, instead of block ID string checking?

File: src/main/java/su/terrafirmagreg/core/common/data/TFGBlocks.java
Comment (Pyritie) [inline src/main/java/su/terrafirmagreg/core/common/data/TFGBlocks.java:742]: I think this might need to be changed too? if the ornate one should also be cutout and not translucent

File: src/main/java/su/terrafirmagreg/core/common/data/items/TrowelItem.java (hunk 1 above)
Comment (Redeix) [reply src/main/java/su/terrafirmagreg/core/common/data/items/TrowelItem.java:68]: Honestly I did this because I am thinking about forking the trowel into a separate mod and I wanted to test how to do an optional dependency

File: src/main/java/su/terrafirmagreg/core/common/data/TFGBlocks.java
Comment (Redeix) [reply src/main/java/su/terrafirmagreg/core/common/data/TFGBlocks.java:742]: Nah ornate it also translucent not cutout

**Review by Pyritie — APPROVED** [review]
