### PR TITLE
Fix stacks of drums not being floaty

### LINKED ISSUE #2814: [🐛]: holding a stack of drums full of lighter than air gases doesn't make you float
### Was this bug reported before?

- [x] No, it was not.

### Version modpack used

0.11.17

### Environment

SP

### New Worlds

Unsure

### Please provide a link to your latest.log, if relevant.

N/A

### Expected Behavior

hold several drum of I.E. Hydrogen in a stack, float away

### Actual Behavior

hold a stack of drums of floaty gas, don't float away, only float away if it's one drum by itself full

### Steps to Reproduce

grab a few drum of hydrogen and stack em' up

### Additional Information

probably just something with NBT data if I had to guess, idk lol

### PR DESCRIPTION
**Pull request by Mqrius**
Stacked fluid containers (count > 1) don't expose FLUID_HANDLER_ITEM capability, so query as a single-item stack instead
Fixes https://github.com/TerraFirmaGreg-Team/Modpack-Modern/issues/2814

### CODE REVIEW

File: src/main/java/su/terrafirmagreg/core/mixins/common/tfchotornot/EventHandlerMixin.java [hunk 1]
```diff
@@ -23,15 +34,38 @@
...
 public class EventHandlerMixin {
 
+    @SuppressWarnings("removal")
+    private static final List<TagKey<Fluid>> OIL_FLUID_TAGS = List.of(
+            TagKey.create(ForgeRegistries.FLUIDS.getRegistryKey(), new ResourceLocation("firmalife", "oils")),
+            TagKey.create(ForgeRegistries.FLUIDS.getRegistryKey(), new ResourceLocation("gtceu", "oil")),
+            TagKey.create(ForgeRegistries.FLUIDS.getRegistryKey(), new ResourceLocation("gtceu", "oil_light")),
+            TagKey.create(ForgeRegistries.FLUIDS.getRegistryKey(), new ResourceLocation("gtceu", "oil_medium")),
+            TagKey.create(ForgeRegistries.FLUIDS.getRegistryKey(), new ResourceLocation("gtceu", "oil_heavy")));
+    private static final boolean IS_APRIL_FIRST = java.time.LocalDate.now().getMonthValue() == 4 && java.time.LocalDate.now().getDayOfMonth() == 1;
```
Comment (Redeix) [inline src/main/java/su/terrafirmagreg/core/mixins/common/tfchotornot/EventHandlerMixin.java]: Maybe this should be an accessible constant so we can use it elsewhere since I know we want to do more April fools stuff

File: src/main/java/su/terrafirmagreg/core/mixins/common/tfchotornot/EventHandlerMixin.java [hunk 2]
```diff
@@ -23,15 +34,38 @@
 @Mixin(value = EventHandler.class, remap = false)
 public class EventHandlerMixin {
 
+    @SuppressWarnings("removal")
+    private static final List<TagKey<Fluid>> OIL_FLUID_TAGS = List.of(
```
Comment (Redeix) [inline src/main/java/su/terrafirmagreg/core/mixins/common/tfchotornot/EventHandlerMixin.java]: We should probably just make a new tag in kubejs for all oils

File: src/main/java/su/terrafirmagreg/core/mixins/common/tfchotornot/EventHandlerMixin.java [hunk 3]
```diff
@@ -23,15 +34,38 @@
...
 
     @Inject(method = "applyEffectsFluid", at = @At("HEAD"), remap = false, cancellable = true)
     private static void tfg$applyEffectsFluid(ItemStack stack, FluidStack fluidStack, Player player, Level level, CallbackInfo ci) {
         if (stack.is(TFGTags.Items.InsulatingContainer)) {
             ci.cancel();
+            return;
+        }
+
+        // Oil floats on water O_O
+w        if (IS_APRIL_FIRST && level.isRainingAt(player.blockPosition().above())
```
Comment (Redeix) [inline src/main/java/su/terrafirmagreg/core/mixins/common/tfchotornot/EventHandlerMixin.java]: TFC has a seperate utility method for getting wether it is raining since it's different than vanilla MC. I can't tell if you are using the right one since I'm on my phone lol. You might want to double check

Comment (Mqrius) [reply src/main/java/su/terrafirmagreg/core/mixins/common/tfchotornot/EventHandlerMixin.java]: Oh didn't know, lemme check

**Comment by Redeix** [comment]
Actually now that I think about it, surely Mojang has a built in variable for if it's April first right? Since they do their own goofy stuff. Maybe not since they release them as whole separate updates

**Comment by Mqrius** [comment]
> Actually now that I think about it, surely Mojang has a built in variable for if it's April first right? Since they do their own goofy stuff. Maybe not since they release them as whole separate updates

Can't find anything that looks like that!

**Review by Redeix — APPROVED** [review]

**Comment by Redeix** [comment]
Now we wait for April 1st to test it 😁
